### ISSUE TITLE
关于自定义button触发scrollTo事件

### ISSUE THREAD

**Issue by BelinChung** [zdying/jquery.jscrollbar#1]
Hi,很高兴能有这么好的插件
我现在有一张长图
希望在图片容器在左右放置“<” ,">"按钮
请问如何对这2个button绑定scrollTo事件？
谢谢

**Comment by zdying** [comment]
@BelinChung 
谢谢对该插件的支持，时间精力有限，没来得及维护文档，带来的不便敬请谅解。

对于该问题，可以试试类似如下的代码：

```
    $('#test').jscrollbar({
            //.....
    });
    var jsb = $('#test').jscrollbar('getObject');

    $xxx.click(function(){
        jsb.scrollBy('x',50); //水平滚动
        //或者
        $('#test').jscrollbar('scrollBy','x',50);
    }
```

**Comment by zdying** [comment]
暂时没有

------------------ 原始邮件 ------------------
发件人: "BelinChung"; 
发送时间: 2014年1月18日(星期六) 下午4:00
收件人: "daiying-zhang/jquery.jscrollbar"; 
抄送: "念在三角湖畔"97532151@qq.com; 
主题: Re: [jquery.jscrollbar] 关于自定义button触发scrollTo事件 (#1)

感谢你的解答，在你的博客里了解到jscrollbar 适应于并列的DIV，而非单一的image
 本人愚昧，不知道有没有demo可以做参考呢？

&mdash;
